### PR TITLE
Simplify factory.Django._get_or_create

### PR DESCRIPTION
**Pull request by francoisfreitag**

### CODE REVIEW

**Comment by rbarrois** [comment]
Hi,

I think we should add the rationale for this change in the commit description ;)

This extension point is used by some outside code, see https://github.com/search?q=_get_manager%28cls&type=Code for examples.

It is also documented in the recipes section: https://factoryboy.readthedocs.io/en/latest/recipes.html#custom-manager-methods

**Comment by francoisfreitag** [comment]
Hi Raphaël, thanks for the review.

We [are still using `_get_manager()`](https://github.com/FactoryBoy/factory_boy/pull/545/files#diff-64b44bb5f22c8fa5796f70d51e34a3aeR159) in `_create()`, which delegates to `_get_or_create()`. This commit avoids calling `_get_manager()` twice (a first time during `_create()` and a second during `_get_or_create()`). Instead, the result of the first call to `_get_manager()` is now passed to `_get_or_create()`.

> This extension point is used by some outside code, see https://github.com/search?q=_get_manager%28cls&type=Code for examples.

Searching for `_get_or_create()` extensions, I did find some matches.
https://github.com/search?q=_get_or_create%28cls%2C+model_class++language%3APython&type=Code
Example match: https://github.com/bitcaster-io/bitcaster/blob/a6c0783a9fa7ae3ba485c8a242dd295f8f82e7ab/src/bitcaster/utils/tests/factories.py#L129

I agree this change in a private API could be documented, I added an entry to the changelog.

Ready for review.

**Comment by federicobond** [comment]
Hi @francoisfreitag, I would like to better understand this change. I worry that the performance impact is not enough to justify a change to the API, even though the method is marked as private. As with other private factory_boy methods, they are likely used in several projects both open and closed source.

From the point of view of the library clients, are there any use cases that would be better covered by obtaining a manager instead of a model class in any `_get_or_create` overrides? Let me know what you think.

**Comment by francoisfreitag** [comment]
Hi @federicobond,

My main concern is duplicated logic, an extra maintenance burden, as these lines could get out of sync. This is a private API, users relying on it should not be surprised it changed. With the documentation, upgrading should be extremely simple.

I doubt any significant performance gain will be achieved with this change. Going through the GitHub search results, there aren't many projects for which the upgrade would be difficult. Most project duplicated the method from factory boy, either copying it or committing their venv to the repo. Looking for file named `django.py` helps discarding these. There remain three actual uses. For two of them, changing the argument is enough:

- https://github.com/bitcaster-io/bitcaster/blob/539c99aba401c2b34837a66821fa2b9d991fd01b/src/bitcaster/utils/tests/factories.py#L141
- https://github.com/opennode/waldur-mastermind/blob/06cd4a0d01dc68a7eda374778ed18c756bb41638/src/waldur_openstack/openstack/tests/factories.py#L101

AFAICT, only one project (qstode) actually requires more significant changes:

- https://github.com/piger/qstode/blob/31fac435b63c864b8b2fff14daa59c8269122a72/qstode/test/model_factory.py#L35, which would need to retrieve the model class from the manager. It's not relying on `factory_boy`'s `_get_or_create` implementation, so I'm not sure we should go leaps and bounds to support this use case.

I am still slightly in favor of merging, but don't mind closing this PR if others don't feel the same way.

**Comment by federicobond** [comment]
Hi @francoisfreitag, I understand your concern. If this were an app instead of a library I would be inclined to merge for the reasons given. However, I fear the improvement is not enough to justify having inconsistent signatures between `_create` and `_get_or_create` and breaking other (most likely closed-source) projects. 
``` python
def _create(cls, model_class, *args, **kwargs)
```
Sometimes it's just better to leave a little ugliness on the inside of the library in order to deliver a, consistent API for the users.

What we could do, however, is move the `_get_manager` call down to right above where its used, so we avoid calling it twice in the get_or_create case.

**Comment by federicobond** [comment]
I will exercise a quick call here and include the change to avoid calling `_get_manager` twice but leave out any API changes for the moment. I am open to revisiting this later should the need arise.

Commit will still be attributed to you.

**Pull request closed without merging**
