### PR TITLE
Add a note about using factory.Factory

### LINKED ISSUE #587: Documentation make it look like I've got to inherit factories from factory.Factory
#### The problem
I've spent quite a while trying to figure out why my factory doesn't return saved Django model instance as promised. All the examples [here][1] inherit factories from `factory.Factory`. From what I can see `factory.Factory` doesn't try anything as near as to [saving][2] the model. It looks as if `factory.Factory` is an abstract class (not to be used directly).

[1]: https://factoryboy.readthedocs.io/en/2.11.1/
[2]: https://github.com/FactoryBoy/factory_boy/blob/v2.9.0/factory/base.py#L546

#### Proposed solution
Improve the documentation. Depends on what `factory.Factory` is for. For example, choose the popular ORM to use for examples. Or state clearly before inheriting from `factory.Factory` that it's not to be used with ORMs. And probably explain what `factory.Factory` is for.

### PR DESCRIPTION
**Pull request by x-yuri**
I'd also like to add a link that points to the current version of the documentation on Read The Docs. But that is probably impossible. Should I add a link to https://factoryboy.readthedocs.io/en/latest/orms.html?

Resolves #587.

### CODE REVIEW

**Comment by francoisfreitag** [comment]
Hi, thanks for the suggestion.

Would the following rephrasing, instead of a note, address your concern?

```diff
-Factories declare a set of attributes used to instantiate an object.
+Factories declare a set of attributes used to instantiate a Python object.
```

---

To link across sections of the documentation, Sphinx offers to [cross-reference arbitrary locations](http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-arbitrary-locations).

**Comment by x-yuri** [comment]
Well, to confirm that I've got to unfamiliarize myself with Factory Boy, and try again to see if understand the README correctly.

My point is, the main use case for this library lies in a Django project. But in the README you give examples for plain objects. People would generally regard them as examples of using the library with Django's ORM. So in my opinion either the examples are to be rewritten to use `factory.django.DjangoModelFactory`, or there must be a note about Django ORM like in the PR. Not everybody will read the whole documentation before starting using the library.

But that's apparently the way I see it. You're free to reject the PR, and that's okay :)

**Comment by francoisfreitag** [comment]
The [Using factories](https://factoryboy.readthedocs.io/en/latest/#using-factories) section of the README is clearly targeted at ORMs. `.create()` does not make sense for plain Python objects. That is misleading for users who just read the factory definition from [Defining factories](https://factoryboy.readthedocs.io/en/latest/#defining-factories), and is probably what tricked you.

I agree the README needs to be improved. A note looks like band-aid for structural issues in that file. Hopefully I can suggest an update in the upcoming weeks. Ideas and PRs are welcome.

**Comment by francoisfreitag** [comment]
Actually, fixing didn’t take long. If you get the chance, please give your opinion on #627.

**Comment by francoisfreitag** [comment]
#627 superseded this PR, thanks for the contribution!

**Pull request closed without merging**
