### PR TITLE
get_first_or_create implemented

### PR DESCRIPTION
**Pull request by domandinho**

### CODE REVIEW

**Comment by domandinho** [comment]
@rbarrois 
What about this PR?

**Comment by kingbuzzman** [comment]
_I'm just some guy from the internet with 0 authority_

This PR seems unique enough to your use case that I see no reason why it should be added. You can create your own BaseFactoryModel and implement this yourself. #sorry

**Comment by federicobond** [comment]
I second @kingbuzzman here. This indeed appears quite specific to your use case.

**Comment by federicobond** [comment]
I will close this pull request now since the discussion appears stale. Feel free to reopen it if you want to bring new information to it.

**Pull request closed without merging**
