### PR TITLE
Fixes mongoengine depreciation issue

### PR DESCRIPTION
**Pull request by kingbuzzman**
Fixes https://github.com/FactoryBoy/factory_boy/issues/922

* Issue with `mongoengine` throwing a `DeprecationWarning`

### CODE REVIEW

**Comment by francoisfreitag** [comment]
Thanks! It looks like the tests are now passing. :tada: 

Do you have an understanding of the cause of that deprecation warning? Is there a change to make in `factory_boy` to better use mongoengine and avoid this warning?

**Comment by kingbuzzman** [comment]
I honestly don't know and have very little knowledge of mongo. I have a big PR that I hope you will accept soon, and this was a blocker. I didn't look into it further than just getting the tests to go green.

**Comment by francoisfreitag** [comment]
Nice, we came to the same conclusion. https://github.com/FactoryBoy/factory_boy/pull/924

**Comment by kingbuzzman** [comment]
LOL, great minds think alike ;)

**Comment by kingbuzzman** [comment]
PS. i used single quotes because the rest of the code uses single quotes in _that_ file.

**Comment by francoisfreitag** [comment]
Too used to Black I guess. It’s been on the table for a while https://github.com/FactoryBoy/factory_boy/pull/843.

**Comment by kingbuzzman** [comment]
Are yo merging # 924 then? Do I close this one?

**Comment by francoisfreitag** [comment]
Yes, please. I marked you as a co-author for #924.

**Comment by kingbuzzman** [comment]
Ugh, stupid button :P

**Pull request closed without merging**
