### PR TITLE
Move version to setup.cfg

### PR DESCRIPTION
**Pull request by francoisfreitag**
Enforces a declarative style for version. Be closer to the default setuptools behavior.

### CODE REVIEW

**Comment by federicobond** [comment]
Change looks good, please rebase.

**Comment by francoisfreitag** [comment]
Rebased, fixed version to be `2.12.1.dev0` (was 2.12.1, leftover from testing `fullrelease`).

**Comment by rbarrois** [comment]
I disagree with this: it breaks the `import factory; factory.__version__` way of getting the current version of factory_boy.

Can we find a way to restore that regression?

**Comment by francoisfreitag** [comment]
Can you expand on the use case for getting the current version of `factory_boy`? I would like to understand the issue to see if we can improve on the previously complex solution.

**Comment by rbarrois** [comment]
Pretty simple: if a third party library (say django_factory_boy or pytest_factory_boy) needs to work around API changes in factory_boy, it could be simpler for them to base that logic around the version, e.g:
```python
import factory

if factory.__version__.split('.')[0] <= 2:
    # Add backwards compat for pre-v3 factory_boy
```

**Comment by francoisfreitag** [comment]
What do you think of documenting a standard way that does not depend on a library hook, such as the following?

```python
>>> import pkg_resources
>>> pkg_resources.get_distribution('factory_boy').version
'2.12.0'
```

**Comment by francoisfreitag** [comment]
If the above is not sufficient, `setup.cfg` offers an `attr:` directive:

> attr: - Value is read from a module attribute. attr: supports callables and iterables; unsupported types are cast using str().

**Comment by rbarrois** [comment]
Oh, now that's promising! I'm a bit wary of using `pkg_resources`, because the way it fetches version numbers doesn't seem very explicit to me.

On the other hand, I agree with the removal of custom parsing code from `setup.py`; basically, my checklist is:
- Must work natively with *zest.releaser*;
- Must be easily reachable from `factory.__version__`
- Doesn't add new runtime dependencies (which `pkg_resources` would, being part of `setuptools`; but that's a dependency we can live with :wink:)

**Comment by francoisfreitag** [comment]
Implemented as https://github.com/FactoryBoy/factory_boy/pull/676/.

**Pull request merged**
