### PR TITLE
Remove support for end-of-life Python 2.7

### PR DESCRIPTION
**Pull request by jdufresne**
Python 2.7 went end-of-life 2020-01-01 🎉. It is no longer receiving updates, including for security issues. For additional details on support Python versions, see:

Supported: https://devguide.python.org/#status-of-python-branches
End-of-life: https://devguide.python.org/devcycle/#end-of-life-branches

Removing support for Python 2.7 will reduce testing and maintenance resources while allowing the library to move towards modern Python conventions.

Allows the following cleanups:

- Remove `compat.py` modules. The shims are now unnecessary.
- Remove `mock` test dependency. Use `unittest.mock` instead.
- Remove `-*- coding: utf-8 -*-` encoding cookie from source files. Source files default to utf-8 in Python 3.
- Remove unnecessary `__future__` imports.
- Remove `(object)` from class definitions. Python 3 has no old-style classes.
- Use Python 3 simplified `super()` syntax.
- Use Python 3 metaclass syntax.

Using pypinfo, we can show the PyPI download statistics for the last month. It shows total Python 2 usage below 20% and shrinking.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.7            |  38.36% |        369,649 |
| 3.6            |  33.88% |        326,559 |
| 2.7            |  16.70% |        160,905 |
| 3.8            |   6.84% |         65,965 |
| 3.5            |   3.84% |         37,011 |
| 3.4            |   0.36% |          3,497 |
| 3.9            |   0.01% |            102 |
| 2.6            |   0.00% |             23 |
| 3.3            |   0.00% |             17 |
| Total          |         |        963,728 |

### CODE REVIEW

**Comment by rbarrois** [comment]
Thanks for the amazing work! I'll schedule an in-depth review soon.

How should we proceed with releasing that version? Do we go for a major version bump?
And in that case, are there other changes we would like to merge in as well?

**Comment by jdufresne** [comment]
I think a major version bump makes sense. It can even wait until after the next minor version if that helps. I'll rebase if a new release is cut.

> And in that case, are there other changes we would like to merge in as well?

While working through the code, I noticed several comments of the form "Deprecated ... remove ...". So if there is a major version bump, it might be a good time to remove those as well.

**Comment by jeffwidman** [comment]
I'm 👍 *2 on this. 

Definitely should be a major version bump.

> While working through the code, I noticed several comments of the form "Deprecated ... remove ...". So if there is a major version bump, it might be a good time to remove those as well.

Agreed.

**Comment by jeffwidman** [comment]
@jdufresne can you fix the conflict? 

After that, let's merge this so that we don't run the risk fo more conflicts and don't waste folks time maintaining code that will soon be removed.

**Comment by jdufresne** [comment]
Thanks. Rebased.

**Comment by jeffwidman** [comment]
💥 And we are now in the Python3-only future!

**Comment by jeffwidman** [comment]
I noticed the readme still shows a badge as python 2 compatible, but when I tried to fix, that pulls directly from the Pypi trove classifiers, so won't auto-update until a new release happens.

**Pull request merged**
