### PR TITLE
Comments should match the parameter names

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by rbarrois** [comment]
Good catch!
Can you investigate why the "examples" check fails?

Thanks :)

**Comment by cclauss** [comment]
This failure appears to be unrelated to editing a docstring.  https://github.com/FactoryBoy/factory_boy/blob/master/examples/flask_alchemy/test_demoapp.py#L14 seems to be failing to create a database because it is being run outside of a Flask application context.  I test using pytest to avoid such confusing situations.

**Review by kingbuzzman — APPROVED** [review]
@cclauss the issue has been fixed on master.

LGTM

**Comment by kingbuzzman** [comment]
@cclauss sorry i wasn’t clear enough, the CI issue you encountered has been fixed on master. This change is still very much needed. Apologies.

**Comment by cclauss** [comment]
I do not have the rights to reopen this.  Do you.

Ci non, je le fais.

**Pull request closed without merging**
