### PR TITLE
Create ImageField files from a callable

### PR DESCRIPTION
**Pull request by tomleo**
Allow dynamic creation of ``factory.django.ImageField`` fields
by passing a function that returns an image file object.

### CODE REVIEW

**Comment by rbarrois** [comment]
Hi!

This looks great; but shouldn't we move this feature to the ``factory.django.FileField`` level instead?

**Comment by tomleo** [comment]
Hey @rbarrois, I implemented this feature on `factory.django.FileField` but only documented it on `ImageField`. Made an update to the docs here https://github.com/FactoryBoy/factory_boy/pull/320/commits/02421885feabbcaf2740f414c1dff1e7d7033d64

**Comment by rbarrois** [comment]
Awesome! Would you have the time to add a test of the feature?
Otherwise, I'll add it myself by the end of the week.

**Comment by tomleo** [comment]
@rbarrois Added a test for the feature

**Comment by tomleo** [comment]
Thanks for the quick feedback and merge @rbarrois!

I noticed the changelog's last logged update was on `2016-07-10` but the python wheel was last uploaded `2016-04-19`. Any estimate as to when the build on PyPi will be updated?

**Pull request merged**
