### PR TITLE
Combine similar environments lines in tox.ini

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Review by francoisfreitag — APPROVED** [review]

**Comment by rbarrois** [comment]
The lines where split because each Django version might support different Python versions; it's a way to be explicit about "We support Django N with Python versions P, because that's what Django supports".

I don't mind merging the lines, but we'll likely split them again when Django 3.2 comes out — or as we add Python 3.9, which is unlikely to be supported with Django 2.2.

**Comment by jdufresne** [comment]
Would you prefer then to combine pypy3 with the three lines above it and keep a line per Django?

**Comment by jdufresne** [comment]
@rbarrois I separated the lines out, is that how you had it in mind? I can either keep the 2nd commit or drop it depending on your preference.

**Review by rbarrois — APPROVED** [review]

**Comment by rbarrois** [comment]
@jdufresne thanks! The final version looks great :)

**Pull request merged**
