### PR TITLE
Simplify Django imports

### PR DESCRIPTION
**Pull request by francoisfreitag**
The `django` module is no longer imported by `factory.__init__`.
Importing `factory.django` makes it obvious Django is required. Django
not being installed can raise an `ImportError`.

### CODE REVIEW

**Comment by rbarrois** [comment]
This change is likely to break lots of code, much more than removing `factory.DjangoModelFactory`.
Users would have to replace `import factory` with `import factory; import factory.django`.

What are the expected benefits from this change, both for the project's users and maintainers?

**Comment by francoisfreitag** [comment]
This PR is meant to illustrate the simplification allowed by removing the alias `factory.django`. It’s related to https://github.com/FactoryBoy/factory_boy/pull/753#issuecomment-660079929.

**Comment by rbarrois** [comment]
@francoisfreitag I've got an idea to reduce avoidable changes for users: we could add this at the top of `factory/__init__.py`:

```python
try:
    from . import django
except ImportError:
    pass

try:
    from . import alchemy
except ImportError:
    pass
```

This allows users of factory_boy + django to still be able to use `import factory; factory.django` (similar to `import os; os.path`), but allows us to simplify the code in `factory/django.py` and co.
Tests run fine with this arrangement, too ;)

What do you think?

**Comment by francoisfreitag** [comment]
I like that better than reverting the removal of deprecated imports. It does not push the burden of checking for dependencies to the submodules, and lets `__init__` handle it.

Considering Django or SQLAlchemy as optional modules, ideally the factory module should not try to import them at all. But this ship has sailed, many users are doing `import factory; factory.django.DjangoModelFactory` and I don’t think its worth break users imports just for purity and to avoid a bit of complexity in `factory.__init__`.

**Comment by francoisfreitag** [comment]
Opened PR https://github.com/FactoryBoy/factory_boy/pull/766 for https://github.com/FactoryBoy/factory_boy/pull/760#issuecomment-667048804.

**Pull request merged**
