### PR TITLE
Verify database entries in Django get_or_create tests

### PR DESCRIPTION
**Pull request by francoisfreitag**
Be more specific about expected objects in the database.

### CODE REVIEW

**Comment by federicobond** [comment]
I don't see how the previous checks would be insufficient to assert for correct behavior. Can you tell me a little bit more about what motivated the change?

**Comment by francoisfreitag** [comment]
`self.assertEqual(2, models.MultifieldModel.objects.count())` only asserts the number of objects in the database, not the objects specifically. Asserting what slugs are present is more precise and less likely to yield false positives, in case objects in the database are not the expected ones (leakage from other tests, modification of the slug in the factory, or whatever mistake).

The original model has a unique constraint on `slug`. That makes the model definition an element of the test, because it ensures `obj1` and `obj2` are not both present in the database.
IMHO, tests should be as precise and contained as possible.

**Comment by federicobond** [comment]
Got it. Would it make the code cleaner to use `assertQuerysetEqual` instead of a helper method?

**Comment by francoisfreitag** [comment]
With an `assertQuerysetEqual`, a `transform` would be called on each model to extract the `slug` (because the `repr` is not helpful for the test), where `values_list` only fetches the `slug` column from the DB.
Not a strong opinion, just a preference.

**Comment by federicobond** [comment]
I would optimize for test readability in isolation in this case. `_get_slugs` is ambiguous and requires looking up another method to understand the test.

**Comment by francoisfreitag** [comment]
`_get_slugs()` was introduced to avoid duplicating the QuerySet construction. Perhaps that was too much. Uses of `_get_slugs()` were replaced with the actual QuerySet to help reading tests in isolation.
Ready for review.

**Pull request merged**
