### PR TITLE
Pgs/pypy3 support

### PR DESCRIPTION
**Pull request by sideris**
Pull Request for #364

Adding support for PyPy

### CODE REVIEW

**Comment by sideris** [comment]
Hm. Seems pypy3 has some issues with Django 1.11. Will investigate further. Weird as tox locally runs quite nicely

**Comment by jeffwidman** [comment]
Also, feel free to squash your commits that are logically the same and force push to this branch--github will see that and update this PR. It's not required, now that GH lets maintainers squash and merge, but it is general good etiquette. 😄

**Comment by sideris** [comment]
For documentation purposes:

> Django 1.11 supports  2.7, 3.4, 3.5, or 3.6.

 The latest pypy version is Python 3.3.5 (not for all platforms). 

Same for 1.10 which supports 3.4 or 3.5 :/

**Comment by rbarrois** [comment]
@sideris thanks for looking into this!

It looks like Pypy has released version 5.8 (https://morepypy.blogspot.fr/2017/06/pypy-v58-released.html), with Python3.5 support.

According to travis-ci bug, it should be possible to use more recent Pypy versions under travis:
- https://github.com/travis-ci/travis-ci/issues/7507
- https://travis-ci.org/BanzaiMan/travis_production_test/jobs/241402194/config (linked from above).

If you're still interested, would you mind checking if those updated configurations still work?

Thanks again for your help :smiley:

**Comment by sideris** [comment]
@rbarrois Hi! I am very glad to hear this. I will work on it when I get some time :D

Thank you!

**Comment by sideris** [comment]
@rbarrois I will squash the commits and then it's ripe for picking.

**Comment by jeffwidman** [comment]
I see merge conflicts here, can you rebase?

**Comment by kevin-brown** [comment]
> I see merge conflicts here, can you rebase?

I don't see any merge conflicts from my side.

**Comment by sideris** [comment]
@jeffwidman I can't see any conflicts. I will squash the commits and see if there's anything

**Comment by jeffwidman** [comment]
Github is refusing the merge with the message:
> This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.
Rebase and merge 

So please rebase on top of master, fix the conflicts and then force-push to the PR branch to update the PR.

**Comment by sideris** [comment]
I preferred to merge, so I don't have to "replay" few months of conflicts.

**Comment by rbarrois** [comment]
Thanks!

I've rebased it and merged, as e55493d7aa7aebead8fd5f689503477cb0c00e0e :)

**Pull request closed without merging**
