### PR TITLE
Remove ignored Python nightly build

### PR DESCRIPTION
**Pull request by federicobond**

### CODE REVIEW

**Comment by francoisfreitag** [comment]
Is nightly removed because travis always runs nightly with a stale image of `3.8.0a3+`? If so, please mention it in the commit message.

**Comment by federicobond** [comment]
Yes, I should have made my reasoning more clear. I didn't think the nightly build was adding much value since it is failing all the time.

Now that I have given it more thought, though, I can see some advantages of checking ahead of time if we are running into issues with future Python versions, even if we don't enforce green builds.

**Comment by francoisfreitag** [comment]
Checking against nightly makes sense, but travis version of nightly Python is a stale one which does not represent the current state of Python's development version.
I'm inclined to remove the nightly check, I would just like the reason for removal to be part of the commit message (and perhaps the commit title could be updated to match them).

**Comment by francoisfreitag** [comment]
@federicobond Is it okay if I update the commit message and merge this?

**Comment by federicobond** [comment]
Sure! Go ahead. Thank you!

**Pull request merged**
