### PR TITLE
Document example that uses factory_boy with Django GenericForeignKeys

### PR DESCRIPTION
**Pull request by rmeritz**
I created factories today for models with Django GenericForeignKeys. It was possible to do but not entirely straightforward. I think anyone else who wants to make a factory for a model with a GenericForiegnKey would appreciate some documentation of how to create a factory for such a relationship. This pull requests adds an example that shows how to do that.

I'm not sure if the way that did it is the best way. If there is a better way I would appreciate advice/documentation on how to do it.

### CODE REVIEW

**Comment by jeffwidman** [comment]
@rbarrois Any reason not to merge this? It does make the docs a little more brittle, but I know when I was coming up to speed on FB, I certainly wished there were more examples out there of how to do things.

**Comment by rbarrois** [comment]
The idea looks good (and has been added to the examples folder through #356 !).

However:
- The ``docs/orms.rst`` document is the API reference for ORM extensions; we should put that section in a  new part ("Django tips"?) of the ``docs/recipes.rst`` file
- In order to ensure that examples in the doc are properly tested, we should use sphinx' [``.. literalinclude::``](http://www.sphinx-doc.org/en/1.5.1/markup/code.html#directive-literalinclude) feature to import the actual (tested) example code.

**Comment by demonno** [comment]
I have added this in `docs/recipes.rst` #368

**Comment by rbarrois** [comment]
Thanks @demonno for fixing it.

@rmeritz this has now been merged, with nice tests at that!

I'm really, deeply sorry for taking so long to fix it, though :confused:

**Pull request closed without merging**
