### PR TITLE
fix seeding of random

### PR DESCRIPTION
**Pull request by chongkim**
Creating a class with multiple Fakers and LazyAttributes will not give consistent results when seeding for randomness.

* I've modified Faker so the constructor calls `super()` so the `_creation_counter` is incremented.
* I've updated the builder so it creates the attributes in the order it was created.
* I've updated factory/random to set the faker random seed because the faker registry may be empty
* I've updated the test for `RepeatableRandomSeedFakerTest`

### CODE REVIEW

**Comment by chongkim** [comment]
NOTE: When you run the tests (`make test`) before doing the pull request, it will pass, but it will fail if you run `python -m unittest tests.test_using.RepeatableRandomSeedFakerTests`.

**Comment by ashleywaite** [comment]
I noted there are two other declarations that do not call `super()`, and thus do not trigger `OrderedBase`. 

Here, in `Maybe`, https://github.com/FactoryBoy/factory_boy/blob/master/factory/declarations.py#L433-L436

And here, in `SimpleParameter`, https://github.com/FactoryBoy/factory_boy/blob/master/factory/declarations.py#L485-L486

Should these also be updated to ensure order is always preserved?

**Comment by chongkim** [comment]
Thanks @ashleywaite.  I've added the calls to super to both of them

**Comment by ashleywaite** [comment]
Currently will break when you are attempting to pass provider_kwargs in, as they will be propagated to OrderedBase, which will propagate them to object, which doesn't accept any kwargs.

As there could theoretically be cases where something wants to rely on OrderedBase to pass along kwargs (ie, diamond inheritance), then I suspect Faker eating them as assumed provider args is the right fix.

So remove the **kwargs from the super call in Faker. :)

**Comment by chongkim** [comment]
Thanks again @ashleywaite I'm glad you caught that.

**Comment by jeffwidman** [comment]
@rbarrois can you take a look? I'm not too familiar with this part of the internals...

**Comment by rbarrois** [comment]
@chongkim thanks for your PR, it helped me to find the proper source of the issue :)

I have opted for a slightly different approach, so I'm closing this PR ;)

**Pull request closed without merging**
