### PR TITLE
Adding support for Django update_or_create

### PR DESCRIPTION
**Pull request by m-szczepaniak**

### CODE REVIEW

**Comment by federicobond** [comment]
@m-szczepaniak thanks for submitting a pull request! Do you have a good use case for this feature?

The problem I see with it is that it tends to introduce ordering dependencies in the tests. You are bound to get different results depending on which factory ran before.

Within a test case, you can always run `update_or_create` by yourself if you need that behavior.

**Comment by federicobond** [comment]
I am going to close this pull request since it hasn't received attention for a while. Feel free to reopen if you want to continue discussing it.

**Comment by Menda** [comment]
Hi @federicobond . In our case, we need this feature for replacing fixtures when populating the basic data structure that our application needs.

Our application needs to have some minimum data to work, like groups, sample users, etc. This data we would not like to have in fixtures, but in Factories, as we can maintain them better. Sometimes we need to update some info in the Factory, so this is where it is really practical for us to have this feature.

I don't see the problem with the ordering dependencies as you see, frankly.

**Comment by youtux** [comment]
+1, for the exact reason mentioned in https://github.com/FactoryBoy/factory_boy/pull/558#issuecomment-498959730

**Comment by francoisfreitag** [comment]
Also -1 on this one.

The issue with the order of dependencies:

```python
# factories.py
class UserFactory(factory.DjangoModelFactory):
    class Meta:
        model = User
        django_update_or_create = ["email"]

    # Contrived example.
    email = "foo@bar.com"

# tests.py
def test_ordering():
    user1 = UserFactory.create(is_staff=False)
    user2 = UserFactory.create(is_staff=True)
    # The Python instance for user1 no longer reflect the database.
    self.assertIs(user1.is_staff, False)
    self.assertIs(user2.is_staff, True)

    user1.refresh_from_db()
    assertIs(user1.is_staff, True)

    # Here’s the ordering trick: if you create user2 before user1,
    # `is_staff` would be `False` in the database. So you get a different
    # situation in the database depending on what order you’ve called the
    # factories.
```

Obviously, the contrived example makes it easy to spot the issue. With a bit of imagination, one might envision the value coming from traits, maybes, or nested subfactories, in a more complete codebase with a more involved setup. That tool would make it fairly easy to create subtle bugs in the codebase.

If you’re looking into a way to generate your data, I would recommend creating the objects directly with the expected values, instead of going back and updating them. That’ll be more efficient (less queries), clearer (the expected state is declared in one place, instead of spread across multiple calls), and avoids the addition of this dangerous tool to the library.

Unless you can come up with a use case that’s actually hard to build without it, please share it, so we can discuss it.

**Comment by youtux** [comment]
You could make a very similar argument for "django_get_or_create":

```

# factories.py
class UserFactory(factory.DjangoModelFactory):
    class Meta:
        model = User
        django_get_or_create = ["email"]

    # Contrived example.
    email = "foo@bar.com"

# tests.py
def test_ordering():
    user1 = UserFactory.create(is_staff=False)
    user2 = UserFactory.create(is_staff=True)
    # The Python instance for user2 did not get is_staff=True
    self.assertIs(user1.is_staff, False)
    self.assertIs(user2.is_staff, True) # breaks
```

So, shall we remove "django_get_or_create" too?

I think these modes (update_or_create, get_or_update) are to be used in very specific use cases, and the user should be aware of the implications.

**Comment by youtux** [comment]
An actual use case for me is for a code base that deals with Currency models. We load these models initially from a cab file in our test suite, but some tests need to slighly modify attributes of a currency.

The only way to do that is by doing this:

```
c = CurrencyFactory()
c.enabled = False

... # rest of the test
```

rather than a more factory oriented:

```
c = CurrencyFactory(enabled=False)

# rest of the test
```


Note that this is a very trivial example, but it would make code much easier when the parametrization goes deeper, like `CustomerFactory(display_currency__enabled=False`. In this case you would have to first instantiate the currency, modify it, and then pass it to the CustomerFactory, instead of just having this one line.

**Comment by francoisfreitag** [comment]
> You could make a very similar argument for "django_get_or_create":

I haven’t found a use case for `get_or_create` that would I find useful, but this ship has sailed. The test environment is controlled by developers, so we should be able to tell beforehand whether an object is present in the database or not. I guess that’s why I’m not finding both methods useful.

At least, `get_or_create` does not touch the state of the database, so besides the risk of wasting queries and a few surprises (like the one you’ve pointed to), it causes little harm. `update_or_create` can cause more pain, by desynchronizing the objects and the database, introducing subtle breakage.

For the test you’re suggesting, why not issue an update query at the beginning of the test? That would be valid for the entire test, get rolled back (assuming you’re using django `TestCase`), and be explicit.

**Comment by youtux** [comment]
> For the test you’re suggesting, why not issue an update query at the beginning of the test? That would be valid for the entire test, get rolled back (assuming you’re using django TestCase), and be explicit.

Of course, you can even override `DjangoFactory._create` to do a `setattr(...)` on each attribute, that would work as well since the transaction would be rolled-back at the end of the test.
But this is about having this possibility out of the box with FactoryBoy.

@federicobond could you re-evaluate opening this PR again, given the use-case I provided in https://github.com/FactoryBoy/factory_boy/pull/558#issuecomment-1564884715?

**Pull request closed without merging**
