### PR TITLE
fix: fix issue #965, use default when getting Faker locale

### LINKED ISSUE #965: KeyError: 'locale'
#### Description
KeyError: 'locale' generated when calling Faker.
factory/faker.py:46: KeyError
Seems that the `extra` dictionary is empty, but `locale` key is expected.

#### To Reproduce
running unit test with tox
python 3.10; factory-boy==3.2.1 faker==13.15.0

##### Model / Factory code
```python
@pytest.fixture
def unique_dominant_factors():
  return list(set(DominantFactorsFactory.create_batch(3)))

@pytest.fixture
def portfolio_values_per_dominant_factors(unique_dominant_factors):
    scenario_ids = np.array([3, 4, 5, 6, 7, 8, 9, 10])
    portfolio_values_per_dominant_factors = PortfolioValuesPerDominantFactors(
        scenario_ids=scenario_ids, dominant_factors=unique_dominant_factors
    )
    rng = np.random.default_rng(seed=2021)
    for i in range(len(unique_dominant_factors) - 1):
        portfolio_values_per_dominant_factors.add_instrument_values_by_factor_name(
            unique_dominant_factors[i], rng.normal(size=8)
        )
    portfolio_values_per_dominant_factors.add_instrument_values_by_factor_name(
        unique_dominant_factors[-1], np.zeros(8)  # Portfolio value 0 can also occur
    )

    return portfolio_values_per_dominant_factors
```

##### The issue
*Add a short description along with your code*

```python

    @pytest.fixture
    def unique_dominant_factors():
>       return list(set(DominantFactorsFactory.create_batch(3)))

tests/repositories/test_portfolio_values_per_dominant_factors_repository.py:14:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.tox/py3/lib/python3.10/site-packages/factory/base.py:540: in create_batch
    return [cls.create(**kwargs) for _ in range(size)]
.tox/py3/lib/python3.10/site-packages/factory/base.py:540: in <listcomp>
    return [cls.create(**kwargs) for _ in range(size)]
.tox/py3/lib/python3.10/site-packages/factory/base.py:528: in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
.tox/py3/lib/python3.10/site-packages/factory/base.py:465: in _generate
    return step.build()
.tox/py3/lib/python3.10/site-packages/factory/builder.py:258: in build
    step.resolve(pre)
.tox/py3/lib/python3.10/site-packages/factory/builder.py:199: in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
.tox/py3/lib/python3.10/site-packages/factory/builder.py:344: in __getattr__
    value = value.evaluate_pre(
.tox/py3/lib/python3.10/site-packages/factory/declarations.py:477: in evaluate_pre
    choice = self.decider.evaluate(instance=instance, step=step, extra={})
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <factory.faker.Faker object at 0x7f3843200df0>
instance = <Resolver for <BuildStep for <StepBuilder(<FactoryOptions for DominantFactorsFactory>, strategy='create')>>>
step = <BuildStep for <StepBuilder(<FactoryOptions for DominantFactorsFactory>, strategy='create')>>, extra = {}

    def evaluate(self, instance, step, extra):
>       locale = extra.pop('locale')
E       KeyError: 'locale'


```

#### Notes
Factory-boy version 3.0.1 works properly

### PR DESCRIPTION
**Pull request by skarzi**
<details><summary>Output of a new regression test failure on master branch</summary>
<p>

```
ERROR: test_locale_issue_in_evaluate (tests.test_regression.FakerRegressionTests)
Regression test for `KeyError: 'locale'` raised in `evaluate`.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/skarzi/dev/github/factory_boy/tests/test_regression.py", line 72, in test_locale_issue_in_evaluate
    author = AuthorFactory()
  File "/Users/skarzi/dev/github/factory_boy/factory/base.py", line 40, in __call__
    return cls.create(**kwargs)
  File "/Users/skarzi/dev/github/factory_boy/factory/base.py", line 528, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/Users/skarzi/dev/github/factory_boy/factory/base.py", line 465, in _generate
    return step.build()
  File "/Users/skarzi/dev/github/factory_boy/factory/builder.py", line 260, in build
    step.resolve(pre)
  File "/Users/skarzi/dev/github/factory_boy/factory/builder.py", line 201, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "/Users/skarzi/dev/github/factory_boy/factory/builder.py", line 346, in __getattr__
    value = value.evaluate_pre(
  File "/Users/skarzi/dev/github/factory_boy/factory/declarations.py", line 493, in evaluate_pre
    choice = self.decider.evaluate(instance=instance, step=step, extra={})
  File "/Users/skarzi/dev/github/factory_boy/factory/faker.py", line 46, in evaluate
    locale = extra.pop('locale')
KeyError: 'locale'
```

</p>
</details> 

Fixes #965

### CODE REVIEW

**Comment by skarzi** [comment]
@francoisfreitag could you please take a look? I have added a regression test and a fix

**Comment by skarzi** [comment]
I have merged the latest `master` so CI should pass now

**Comment by francoisfreitag** [comment]
The CI passes, but this change requires a careful review.

https://github.com/FactoryBoy/factory_boy/pull/828 should have solved the issue, by making sure the context is properly initialized and unrolled. There’s apparently a case that slipped through the net, so this error might be a symptom of a larger issue.

I have had my eyes on it for some time, and I’ll try to get back to you on it next week.

**Comment by skarzi** [comment]
thank you @francoisfreitag, sure it makes sense.
Please let me know if I can help you with anything related to this issue!

**Comment by francoisfreitag** [comment]
Ok, finally found some time to investigate this issue, and I believe I have fixed the root issue (see commit “[Call evaluate_pre() instead of evaluate() on Maybe decider](https://github.com/FactoryBoy/factory_boy/pull/1010/commits/239b3f892d1060d7be32dbdadcaed11423d7cdb2)”).

@rbarrois since you’re the author of https://github.com/FactoryBoy/factory_boy/commit/e19142cb6e049e079cd4af36775715fcda47cb8c, your input would be great! :)

**Pull request closed without merging**
