### PR TITLE
Make a breaking changes summary in change log

### PR DESCRIPTION
**Pull request by francoisfreitag**
Helps users identify breaking changes and the recommended import.

Also, fix a couple formatting issues with the changelog.

### CODE REVIEW

**Comment by rbarrois** [comment]
Reading the ChangeLog, I'm wondering about the gain from removing the `factory.django` / `factory.alchemy` / … aliases.

They allowed for simpler imports, akin to `import os; os.path.join(...)`. What is the benefit (for the project, for the user) in removing them? Is it worth the hassle?

**Comment by francoisfreitag** [comment]
The main benefit is to make each module more isolated.
It avoids loading Django, SQLAlchemy, mogo or mongoengine when importing `factory`. It facilitates dealing with missing dependencies, as Django can now be a prerequisite for importing `factory.django` (same with SQLAlchemy, mogo or mongoengine), whereas modules needed to handle the missing dependency when `factory.__init__` imported them.

Migrating the project developed at my day job took less than half an hour, and it was simply renaming aliases. Not a big effort IMO.

**Comment by francoisfreitag** [comment]
See #760 for simplifications we can make since the aliases were dropped.

Recent changes (59ee6584d8788af065a86aa168e8f42a4e9f3801) to SQLAlchemy module now import directly from the `sqlalchemy` package, without import guards. Guards should be added if we were to keep importing SQLAlchemy in `factory.__init__`.

**Comment by francoisfreitag** [comment]
#766 restores some aliases (e.g. `factory.django`), removed them from the table.

**Comment by rbarrois** [comment]
Merged as 85543a502eed7a3d5de17669a98e761e92a78add

**Pull request closed without merging**
